import{a as y,S as f,i}from"./assets/vendor-D1eTGYtO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const g of a.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&c(g)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const v="https://pixabay.com/api/",L="45140381-2d1d7d148fe8b2b4910dcca17";async function h(s,t=1){try{return(await y.get(v,{params:{key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch{}}function m(s){let t=new f(".gallery a",{overlay:!1,overlayOpacity:.7,nav:!0,captions:!0,captionsData:"alt",captionDelay:350});const o=document.querySelector(".gallery");let c=s.hits.map(e=>`<div class="gallery-list">
      <a href="${e.largeImageURL}">
      <img class="image" src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class ="gallery-list-text">
      <div class="gallery-list-stat">
      <h5>likes</h5>
      <p>${e.likes}</p></div>
      <div class="gallery-list-stat">
      <h5>views</h5>
      <p>${e.views}</p></div>
      <div class="gallery-list-stat">
      <h5>comments</h5>
      <p>${e.comments}</p></div>
      <div class="gallery-list-stat">
      <h5>downloads</h5>
      <p>${e.downloads}</p></div></div></div>`).join("");o.insertAdjacentHTML("beforeend",c),t.refresh()}function w(){const s=document.querySelector(".gallery");s.innerHTML=""}const u=document.querySelector(".gallery-form"),b=document.querySelector(".gallery-input"),n=document.querySelector(".loader"),p=document.querySelector(".load-more-loader"),r=document.querySelector('[data-action="load-more"]');let d="";u.addEventListener("submit",S);r.addEventListener("click",q);const l={page:1,q:"",per_page:15};async function S(s){if(s.preventDefault(),w(),d=b.value.trim(),l.page=1,d===""){i.error({position:"topRight",message:"Please fill the input"}),n.classList.add("hidden"),r.classList.add("is-hidden"),u.reset();return}n.classList.remove("hiden");try{const t=await h(d);t.total===0?(i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),r.classList.add("is-hidden")):(await m(t),t.total<=15?(r.classList.add("is-hidden"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("hidden")):r.classList.remove("is-hidden")),n.classList.add("hiden")}catch{i.error({position:"topRight",message:"Something went wrong. Please try again later"}),n.classList.add("hiden"),r.classList.add("is-hidden")}finally{u.reset()}}async function q(){l.page+=1,r.classList.add("is-hidden"),p.classList.remove("hiden");try{const s=await h(d,l.page);m(s);const o=document.querySelector(".gallery-list").getBoundingClientRect().height;window.scrollBy({top:(o+24)*5,behavior:"smooth"}),l.page*l.per_page>=s.totalHits?(r.classList.add("is-hidden"),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):r.classList.remove("is-hidden")}catch{i.error({position:"topRight",message:"Something went srong. Please try again later."}),p.classList.add("hiden")}finally{p.classList.add("hiden")}}
//# sourceMappingURL=commonHelpers.js.map
